import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";

import NavBar from "@/components/NavBar";
import FooterBar from "@/components/FooterBar";

const poppins = Poppins({ subsets: ["latin"], weight: ["300", "400", "500", "700", "900"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body className={poppins.className}>
        <div className="min-h-screen flex flex-col">
          <NavBar/>
          <main className="flex-grow">{children}</main>
          <FooterBar/>
        </div>
      </body>
    </html>
  );
}
